#!/bin/bash

cd /opt/
mkdir odoo
cd odoo

apt update

apt install curl --yes
apt install wget --yes
apt install unzip --yes
apt install gcc --yes
apt install musl-dev --yes
apt install libxslt-dev --yes
apt install postgresql-10 --yes
apt install python3-dev --yes
apt install python3-venv --yes

curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
apt install nodejs --yes
npm install -g less

wget https://github.com/trung83585715/my-tools/archive/master.zip
unzip master.zip
rm -r master.zip
mv my-tools-master/ my-tool

wget https://github.com/trung83585715/odoo12/archive/master.zip
unzip master.zip
rm -r master.zip
mv odoo12-master/ 12
cd 12

systemctl stop postgresql.service
systemctl start postgresql.service
systemctl enable postgresql.service

python3 -m venv env
source env/bin/activate
./env/bin/pip3 install -r requirements.txt








